[workspace]
members = [
    "crates/common",
    "crates/server",
    "crates/web",
    "crates/examples"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["phonnz <gonzalezm.alfonso@gmail.com>"]
