[workspace]
members = [
    "crates/common",
    "crates/server",
    "crates/web"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"] 