version: '3.8'
services:
  test-db:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: fullrstack_test
    ports:
      - "5432:5432"

  load-test:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["cargo", "bench"]
    depends_on:
      - test-db 