[package]
name = "fullrstack-common"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
time = { version = "0.3", features = ["serde"] }
thiserror = "1.0"

[dev-dependencies]
tokio-test = "0.4"
pretty_assertions = "1.4" 